# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'browserWidget.ui'
#
# Created: Thu Oct 17 22:34:42 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from PyQt4.QtWebKit import QWebView
from PyQt4 import QtWebKit
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWidget(QtGui.QWidget):
    def __init__(self, parent=None):
        super(Ui_mainWidget,self).__init__(parent)
        self.setupUi(self)
    
    def setupUi(self, mainWidget):
        mainWidget.setObjectName(_fromUtf8("mainWidget"))
        mainWidget.resize(956, 707)
        self.layout_main = QtGui.QHBoxLayout(mainWidget)
        self.layout_main.setSpacing(0)
        self.layout_main.setMargin(0)
        self.layout_main.setObjectName(_fromUtf8("layout_main"))
        self.mainFrame = QtGui.QFrame(mainWidget)
        self.mainFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.mainFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.mainFrame.setObjectName(_fromUtf8("mainFrame"))
        self.layout_mainFrame = QtGui.QVBoxLayout(self.mainFrame)
        self.layout_mainFrame.setSpacing(0)
        self.layout_mainFrame.setMargin(0)
        self.layout_mainFrame.setObjectName(_fromUtf8("layout_mainFrame"))
        self.navFrame = QtGui.QFrame(self.mainFrame)
        self.navFrame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.navFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.navFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.navFrame.setObjectName(_fromUtf8("navFrame"))
        self.layout_nav = QtGui.QHBoxLayout(self.navFrame)
        self.layout_nav.setSpacing(0)
        self.layout_nav.setMargin(0)
        self.layout_nav.setObjectName(_fromUtf8("layout_nav"))
        self.navBack_button = QtGui.QToolButton(self.navFrame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../resources/backward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.navBack_button.setIcon(icon)
        self.navBack_button.setObjectName(_fromUtf8("navBack_button"))
        self.layout_nav.addWidget(self.navBack_button)
        self.navForward_button = QtGui.QToolButton(self.navFrame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../resources/forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.navForward_button.setIcon(icon1)
        self.navForward_button.setObjectName(_fromUtf8("navForward_button"))
        self.layout_nav.addWidget(self.navForward_button)
        self.navUrl_textEdit = QtGui.QLineEdit(self.navFrame)
        self.navUrl_textEdit.setObjectName(_fromUtf8("navUrl_textEdit"))
        self.layout_nav.addWidget(self.navUrl_textEdit)
        self.navReload_button = QtGui.QToolButton(self.navFrame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../resources/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.navReload_button.setIcon(icon2)
        self.navReload_button.setIconSize(QtCore.QSize(16, 16))
        self.navReload_button.setObjectName(_fromUtf8("navReload_button"))
        self.layout_nav.addWidget(self.navReload_button)
        spacerItem = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.layout_nav.addItem(spacerItem)
        self.searchType_combo = QtGui.QComboBox(self.navFrame)
        self.searchType_combo.setMaximumSize(QtCore.QSize(45, 16777215))
        self.searchType_combo.setIconSize(QtCore.QSize(14, 18))
        self.searchType_combo.setObjectName(_fromUtf8("searchType_combo"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../resources/google.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchType_combo.addItem(icon3, _fromUtf8(""))
        self.searchType_combo.setItemText(0, _fromUtf8(""))
        self.layout_nav.addWidget(self.searchType_combo)
        self.searchInput_lineEdit = QtGui.QLineEdit(self.navFrame)
        self.searchInput_lineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.searchInput_lineEdit.setObjectName(_fromUtf8("searchInput_lineEdit"))
        self.layout_nav.addWidget(self.searchInput_lineEdit)
        self.layout_mainFrame.addWidget(self.navFrame)
        self.hotbar_frame = QtGui.QFrame(self.mainFrame)
        self.hotbar_frame.setMaximumSize(QtCore.QSize(16777215, 25))
        self.hotbar_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.hotbar_frame.setFrameShadow(QtGui.QFrame.Plain)
        self.hotbar_frame.setObjectName(_fromUtf8("hotbar_frame"))
        self.layout_hotbar = QtGui.QHBoxLayout(self.hotbar_frame)
        self.layout_hotbar.setObjectName(_fromUtf8("layout_hotbar"))
        self.hotbar1_combo = QtGui.QComboBox(self.hotbar_frame)
        self.hotbar1_combo.setFrame(False)
        self.hotbar1_combo.setObjectName(_fromUtf8("hotbar1_combo"))
        self.layout_hotbar.addWidget(self.hotbar1_combo)
        self.hotbar2_combo = QtGui.QComboBox(self.hotbar_frame)
        self.hotbar2_combo.setFrame(False)
        self.hotbar2_combo.setObjectName(_fromUtf8("hotbar2_combo"))
        self.layout_hotbar.addWidget(self.hotbar2_combo)
        self.hotbar3_combo = QtGui.QComboBox(self.hotbar_frame)
        self.hotbar3_combo.setFrame(False)
        self.hotbar3_combo.setObjectName(_fromUtf8("hotbar3_combo"))
        self.layout_hotbar.addWidget(self.hotbar3_combo)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_hotbar.addItem(spacerItem1)
        self.layout_mainFrame.addWidget(self.hotbar_frame)
        self.tabsFrame = QtGui.QFrame(self.mainFrame)
        self.tabsFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.tabsFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.tabsFrame.setObjectName(_fromUtf8("tabsFrame"))
        self.layout_tabsFrame = QtGui.QVBoxLayout(self.tabsFrame)
        self.layout_tabsFrame.setSpacing(0)
        self.layout_tabsFrame.setMargin(0)
        self.layout_tabsFrame.setObjectName(_fromUtf8("layout_tabsFrame"))
        self.tabWidget = QtGui.QTabWidget(self.tabsFrame)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.layout_tab1 = QtGui.QHBoxLayout(self.tab1)
        self.layout_tab1.setSpacing(0)
        self.layout_tab1.setContentsMargins(0, 0, 4, 0)
        self.layout_tab1.setObjectName(_fromUtf8("layout_tab1"))
        self.tab1_webView = QWebView(self.tab1)
        self.tab1_webView.setUrl(QtCore.QUrl(QtCore.QString("http://google.com")))
        self.tab1_webView.setObjectName(_fromUtf8("tab1_webView"))
        self.layout_tab1.addWidget(self.tab1_webView)
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tabs_addNew = QtGui.QWidget()
        self.tabs_addNew.setObjectName(_fromUtf8("tabs_addNew"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../resources/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabs_addNew, icon4, _fromUtf8(""))
        self.layout_tabsFrame.addWidget(self.tabWidget)
        self.tabsStatus_frame = QtGui.QFrame(self.tabsFrame)
        self.tabsStatus_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.tabsStatus_frame.setFrameShadow(QtGui.QFrame.Plain)
        self.tabsStatus_frame.setObjectName(_fromUtf8("tabsStatus_frame"))
        self.layout_status = QtGui.QHBoxLayout(self.tabsStatus_frame)
        self.layout_status.setObjectName(_fromUtf8("layout_status"))
        self.tabsStatusLeft = QtGui.QLabel(self.tabsStatus_frame)
        self.tabsStatusLeft.setObjectName(_fromUtf8("tabsStatusLeft"))
        self.layout_status.addWidget(self.tabsStatusLeft)
        self.tabsStatusRight = QtGui.QLabel(self.tabsStatus_frame)
        self.tabsStatusRight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tabsStatusRight.setObjectName(_fromUtf8("tabsStatusRight"))
        self.layout_status.addWidget(self.tabsStatusRight)
        self.layout_tabsFrame.addWidget(self.tabsStatus_frame)
        self.layout_mainFrame.addWidget(self.tabsFrame)
        self.layout_main.addWidget(self.mainFrame)

        self.retranslateUi(mainWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWidget)

    def retranslateUi(self, mainWidget):
        mainWidget.setWindowTitle(_translate("mainWidget", "Form", None))
        self.navBack_button.setText(_translate("mainWidget", "<", None))
        self.navForward_button.setText(_translate("mainWidget", ">", None))
        self.navReload_button.setText(_translate("mainWidget", "O", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("mainWidget", "Tab 1", None))
        self.tabsStatusLeft.setText(_translate("mainWidget", "TextLabel", None))
        self.tabsStatusRight.setText(_translate("mainWidget", "TextLabel", None))

